services:
  
  client:
    build:
      context: ./client
      target: prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - voidauth
      - backend

  backend:
    build:
      context: ./server
      target: prod
    volumes:
      - ../.offline-notion-volumes/backend/db:/app/db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
  redis:
    image: redis:8.4.0-alpine
    restart: unless-stopped
      
  voidauth: 
    image: voidauth/voidauth:latest
    restart: unless-stopped
    volumes:
      - ../.offline-notion-volumes/voidauth/config:/app/config
      - ../.offline-notion-volumes/voidauth/db:/app/db
    env_file:
      - ./.env
    environment:
      DB_ADAPTER: sqlite

volumes:
  database:
    driver: local
